import React, { useState, useEffect } from 'react';
import { db } from './firebase';
import { collection, addDoc, onSnapshot, query, orderBy, serverTimestamp } from 'firebase/firestore';
import { GoogleGenerativeAI } from "@google/generative-ai";

// CONFIGURACIÓN IA GEMINI (Tu API Key ya integrada)
const genAI = new GoogleGenerativeAI("AIzaSyAXlb2uiqRSzbD9P8GH8XDePExLUfydnAQ");

function App() {
  const [offers, setOffers] = useState([]);
    const [inputUrl, setInputUrl] = useState("");
      const [loadingIA, setLoadingIA] = useState(false);

        // 1. ESCUCHAR LA BASE DE DATOS (En tiempo real)
          useEffect(() => {
              // Usamos 'createdAt' para que los nuevos chollos salgan arriba
                  const q = query(collection(db, "offers"), orderBy("createdAt", "desc"));
                      const unsubscribe = onSnapshot(q, (snapshot) => {
                            const data = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
                                  setOffers(data);
                                      });
                                          return () => unsubscribe();
                                            }, []);

                                              // 2. FUNCIÓN PARA CREAR CHOLLO CON IA
                                                const publicarConIA = async () => {
                                                    if (!inputUrl) return alert("Por favor, pega un enlace de Amazon, Temu o AliExpress");
                                                        setLoadingIA(true);

                                                            try {
                                                                  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
                                                                        
                                                                              // El "instrucción" para la IA
                                                                                    const prompt = `Analiza este enlace y genera un título corto (máx 10 palabras), muy viral y magnético para una web de chollos. Usa emojis. Devuelve SOLO el texto: ${inputUrl}`;
                                                                                          
                                                                                                const result = await model.generateContent(prompt);
                                                                                                      const tituloIA = result.response.text();

                                                                                                            // Guardar en Firebase automáticamente
                                                                                                                  await addDoc(collection(db, "offers"), {
                                                                                                                          title: tituloIA,
                                                                                                                                  url: inputUrl,
                                                                                                                                          price: "Consultar Oferta", // La IA pone esto por defecto
                                                                                                                                                  createdAt: serverTimestamp() // Fecha del servidor para ordenar
                                                                                                                                                        });

                                                                                                                                                              setInputUrl(""); // Limpiar el cuadro
                                                                                                                                                                    alert("¡Chollo publicado con éxito! 🔥");
                                                                                                                                                                        } catch (error) {
                                                                                                                                                                              console.error("Error:", error);
                                                                                                                                                                                    alert("La IA está descansando, pero la conexión a Firebase funciona.");
                                                                                                                                                                                        }
                                                                                                                                                                                            setLoadingIA(false);
                                                                                                                                                                                              };

                                                                                                                                                                                                return (
                                                                                                                                                                                                    <div style={{ background: '#000', color: '#fff', minHeight: '100vh', fontFamily: 'sans-serif', paddingBottom: '50px' }}>
                                                                                                                                                                                                          
                                                                                                                                                                                                                {/* CABECERA ESTILO VIRAL */}
                                                                                                                                                                                                                      <header style={{ textAlign: 'center', padding: '60px 20px' }}>
                                                                                                                                                                                                                              <h1 style={{ fontSize: '3.5rem', fontWeight: '900', fontStyle: 'italic', margin: 0, letterSpacing: '-2px' }}>
                                                                                                                                                                                                                                        VIRALS<span style={{ color: '#ff0050' }}>.</span>
                                                                                                                                                                                                                                                </h1>
                                                                                                                                                                                                                                                        <div style={{ display: 'flex', justifyContent: 'center', gap: '15px', marginTop: '10px', fontSize: '0.8rem', fontWeight: 'bold', color: '#ff0050' }}>
                                                                                                                                                                                                                                                                  <span>AMAZON</span> • <span>TEMU</span> • <span>ALIEXPRESS</span>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                                                                      {/* PANEL DE ADMINISTRADOR (Botón IA) */}
                                                                                                                                                                                                                                                                                            <section style={{ maxWidth: '500px', margin: '0 auto 50px', padding: '25px', background: '#111', borderRadius: '25px', border: '1px solid #333' }}>
                                                                                                                                                                                                                                                                                                    <h2 style={{ fontSize: '1rem', marginBottom: '15px', textAlign: 'center', color: '#eee' }}>✨ Publicar nuevo chollo</h2>
                                                                                                                                                                                                                                                                                                            <input 
                                                                                                                                                                                                                                                                                                                      type="text" 
                                                                                                                                                                                                                                                                                                                                placeholder="Pega el link del producto aquí..." 
                                                                                                                                                                                                                                                                                                                                          value={inputUrl}
                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setInputUrl(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                              style={{ width: '100%', padding: '15px', marginBottom: '15px', borderRadius: '12px', border: 'none', background: '#222', color: '#fff', boxSizing: 'border-box' }}
                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                              <button 
                                                                                                                                                                                                                                                                                                                                                                                        onClick={publicarConIA}
                                                                                                                                                                                                                                                                                                                                                                                                  disabled={loadingIA}
                                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: '100%', padding: '15px', borderRadius: '12px', border: 'none', background: '#ff0050', color: '#fff', fontWeight: 'bold', fontSize: '1rem', cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                              {loadingIA ? "🪄 LA IA ESTÁ CREANDO EL POST..." : "✨ PUBLICAR CON IA"}
                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* FEED DE OFERTAS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <main style={{ maxWidth: '600px', margin: '0 auto', padding: '0 20px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {offers.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ textAlign: 'center', color: '#666' }}>Buscando las mejores ofertas...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            offers.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <article key={item.id} style={{ background: '#111', borderRadius: '20px', padding: '25px', marginBottom: '20px', border: '1px solid #222' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 style={{ fontSize: '1.2rem', margin: '0 0 15px 0', lineHeight: '1.4' }}>{item.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={{ color: '#ff0050', fontWeight: 'bold', fontSize: '1.3rem' }}>{item.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href={item.url} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ background: '#fff', color: '#000', padding: '12px 20px', borderRadius: '10px', fontWeight: 'bold', textDecoration: 'none', fontSize: '0.9rem' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              VER CHOLLO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      